//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupGSteganography.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroupGSteganography.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this slider to adjust the level of corruption th image will experience.The greater the corruption, the longer your hidden message can be. However, the random alterations of the image will be more apparent.
        /// </summary>
        internal static string SteganographyWindow_linkLabel1_LinkClicked_Use_this_slider_to_adjust_the_level_of_corruption_th_image_will_experience_The_greater_the_corruption__the_longer_your_hidden_message_can_be__However__the_random_alterations_of_the_image_will_be_more_apparent {
            get {
                return ResourceManager.GetString("SteganographyWindow_linkLabel1_LinkClicked_Use_this_slider_to_adjust_the_level_of" +
                        "_corruption_th_image_will_experience_The_greater_the_corruption__the_longer_your" +
                        "_hidden_message_can_be__However__the_random_alterations_of_the_image_will_be_mor" +
                        "e_apparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File (*.png)|*.png|Bitmap File (*.bmp)|*.bmp.
        /// </summary>
        internal static string SteganographyWindow_loadHidingImage_PNG_File____png____png_Bitmap_File____bmp____bmp {
            get {
                return ResourceManager.GetString("SteganographyWindow_loadHidingImage_PNG_File____png____png_Bitmap_File____bmp____" +
                        "bmp", resourceCulture);
            }
        }
    }
}
